### ISSUE TITLE
开发模式下页面无法访问

### ISSUE THREAD

**Issue by yqz0203** [yzydeveloper/vite-plugin-multiple-page#7]
```
app1: {
            entry: 'entries/main/index.tsx',
            filename: '/pages/main.html',
            template: 'entries/main/index.html',
            inject: {
              data: {
                title: 'mpa-app1',
              },
            },
          },
```

访问 127.0.0.1:5173/page/main.html 404

**Comment by yzydeveloper** [comment]
开发环境现在不支持使用filename去访问，目前filename只在build会使用

**Comment by lovelyJason** [comment]
![image](https://github.com/user-attachments/assets/32811b98-2f09-490b-ac2a-f052cb9a81ac)
这个为为什么报错我不是很理解。

另外，打包的时候有个问题，
![image](https://github.com/user-attachments/assets/124c906e-1bf4-447f-9898-02fdf8e02323)
打包产物为什么是这样子的啊，我裂开了老铁

**Comment by yzydeveloper** [comment]
> ![image](https://private-user-images.githubusercontent.com/50656459/399212092-32811b98-2f09-490b-ac2a-f052cb9a81ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIwOTItMzI4MTFiOTgtMmYwOS00OTBiLWFjMmEtZjA1MmNiOWE4MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Mzc2MTc5ZTAxZmJiZTRmNmM2Mzk5ZTAzNTM2ODBjZGZjYjE1NDk1MGFhODgyNzBiMTE1YTQyMzQ0Yzk1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tkcEedjNRA8gkMWmoeylnl0CdGUbjaedw6oqn-7AjIQ) 这个为为什么报错我不是很理解。
> 
> 另外，打包的时候有个问题， ![image](https://private-user-images.githubusercontent.com/50656459/399212269-124c906e-1bf4-447f-9898-02fdf8e02323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIyNjktMTI0YzkwNmUtMWJmNC00NDdmLTk4OTgtMDJmZGY4ZTAyMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OGE0MjMyYmJjMDc3MWNiOTIyNWI0YTU5MTQ0YjFiYjhmZTk0OGRiODA5YTg4NDliZDZhMGMwN2MzYjk5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wpo_VcUpNDqlmQYJmekV5KLwFE6UHtM6F_E9SkH1BEE) 打包产物为什么是这样子的啊，我裂开了老铁






```js
const pages = {
    index: {
        entry: 'src/main.ts',
        template: '/index.html',
        filename: 'index.html',
        inject: {
            data: {
                title: 'mpa index'
            }
        }
    },
    apple: {
        entry: 'src/pages/apple/index.js',
        template: '/src/pages/apple/index.html',
        filename: '/pages/apple.html',
        inject: {
            data: {
                title: 'mpa apple'
            }
        }
    },
}
```
pages属性改成这样，vite.build的配置去掉再试试

**Comment by lovelyJason** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50656459/399212092-32811b98-2f09-490b-ac2a-f052cb9a81ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIwOTItMzI4MTFiOTgtMmYwOS00OTBiLWFjMmEtZjA1MmNiOWE4MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Mzc2MTc5ZTAxZmJiZTRmNmM2Mzk5ZTAzNTM2ODBjZGZjYjE1NDk1MGFhODgyNzBiMTE1YTQyMzQ0Yzk1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tkcEedjNRA8gkMWmoeylnl0CdGUbjaedw6oqn-7AjIQ) 这个为为什么报错我不是很理解。
> > 另外，打包的时候有个问题， ![image](https://private-user-images.githubusercontent.com/50656459/399212269-124c906e-1bf4-447f-9898-02fdf8e02323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIyNjktMTI0YzkwNmUtMWJmNC00NDdmLTk4OTgtMDJmZGY4ZTAyMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OGE0MjMyYmJjMDc3MWNiOTIyNWI0YTU5MTQ0YjFiYjhmZTk0OGRiODA5YTg4NDliZDZhMGMwN2MzYjk5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wpo_VcUpNDqlmQYJmekV5KLwFE6UHtM6F_E9SkH1BEE) 打包产物为什么是这样子的啊，我裂开了老铁
> 
> ```js
> const pages = {
>     index: {
>         entry: 'src/main.ts',
>         template: '/index.html',
>         filename: 'index.html',
>         inject: {
>             data: {
>                 title: 'mpa index'
>             }
>         }
>     },
>     apple: {
>         entry: 'src/pages/apple/index.js',
>         template: '/src/pages/apple/index.html',
>         filename: '/pages/apple.html',
>         inject: {
>             data: {
>                 title: 'mpa apple'
>             }
>         }
>     },
> }
> ```
> 
> pages属性改成这样，vite.build的配置去掉再试试

报错
> error during build:
Could not resolve entry module "../../../../index.html".
    at getRollupError (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
    at error (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
    at ModuleLoader.loadEntryModule (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by lovelyJason** [comment]
报错哈、
> error during build:
Could not resolve entry module "../../../../index.html".
    at getRollupError (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
    at error (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
    at ModuleLoader.loadEntryModule (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
    at async Promise.all (index 2)


![image](https://github.com/user-attachments/assets/1808883c-2c3d-43cf-b715-2f659dbaabde)

**Comment by lovelyJason** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50656459/399212092-32811b98-2f09-490b-ac2a-f052cb9a81ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIwOTItMzI4MTFiOTgtMmYwOS00OTBiLWFjMmEtZjA1MmNiOWE4MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Mzc2MTc5ZTAxZmJiZTRmNmM2Mzk5ZTAzNTM2ODBjZGZjYjE1NDk1MGFhODgyNzBiMTE1YTQyMzQ0Yzk1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tkcEedjNRA8gkMWmoeylnl0CdGUbjaedw6oqn-7AjIQ) 这个为为什么报错我不是很理解。
> > 另外，打包的时候有个问题， ![image](https://private-user-images.githubusercontent.com/50656459/399212269-124c906e-1bf4-447f-9898-02fdf8e02323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzMzMDcsIm5iZiI6MTczNTUzMzAwNywicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTIyNjktMTI0YzkwNmUtMWJmNC00NDdmLTk4OTgtMDJmZGY4ZTAyMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0MzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OGE0MjMyYmJjMDc3MWNiOTIyNWI0YTU5MTQ0YjFiYjhmZTk0OGRiODA5YTg4NDliZDZhMGMwN2MzYjk5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wpo_VcUpNDqlmQYJmekV5KLwFE6UHtM6F_E9SkH1BEE) 打包产物为什么是这样子的啊，我裂开了老铁
> 
> ```js
> const pages = {
>     index: {
>         entry: 'src/main.ts',
>         template: '/index.html',
>         filename: 'index.html',
>         inject: {
>             data: {
>                 title: 'mpa index'
>             }
>         }
>     },
>     apple: {
>         entry: 'src/pages/apple/index.js',
>         template: '/src/pages/apple/index.html',
>         filename: '/pages/apple.html',
>         inject: {
>             data: {
>                 title: 'mpa apple'
>             }
>         }
>     },
> }
> ```
> 
> pages属性改成这样，vite.build的配置去掉再试试

这是我的配置，老铁你看下

```ts
import { defineConfig, normalizePath } from 'vite';
import viteVue from '@vitejs/plugin-vue';
import viteVueJsx from '@vitejs/plugin-vue-jsx';
import {resolve, dirname} from 'node:path';
import {fileURLToPath} from "node:url";
// import {createPages, createMpaPlugin} from "vite-plugin-virtual-mpa";
// import mpa from 'vite-plugin-mpa'
import mpaPlugin from 'vite-plugin-mpa-plus'
import type { Rewrite, Pages } from 'vite-plugin-mpa-plus'

const __dirname = dirname(fileURLToPath(import.meta.url))
console.log("__dirname", __dirname)

const rewrites: Array<Rewrite> = [{ from: /\/apple/, to: '/src/pages/apple/index.html' }]
const pages = {
  index: {
    entry: 'src/main.ts',
    template: '/index.html',
    filename: 'index.html',
    inject: {
      data: {
        title: 'mpa index'
      }
    }
  },
  apple: {
    entry: 'src/pages/apple/index.ts',
    template: '/src/pages/apple/index.html',
    filename: '/pages/apple.html',
    inject: {
      data: {
        title: 'mpa apple'
      }
    }
  },
}
export default  defineConfig({

  server: {
    proxy: {
      '/api': {
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
        target: 'http://localhost:8000/api/v1',
        // target: 'https://apifoxmock.com/m1/5565059-5242221-default/api/v1',
        ws: true,
      },
    },
  },
  plugins: [
    viteVue(),
    viteVueJsx(),
    mpaPlugin({
      pages,
      historyApiFallback: {
        rewrites
      }
    })
  ],
})

```

vite dev就能跑，vite build报错

**Comment by yzydeveloper** [comment]
> 报错哈、
> 
> > error during build:
> > Could not resolve entry module "../../../../index.html".
> > at getRollupError (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
> > at error (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
> > at ModuleLoader.loadEntryModule (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
> > at async Promise.all (index 2)
> 
> ![image](https://private-user-images.githubusercontent.com/50656459/399215831-1808883c-2c3d-43cf-b715-2f659dbaabde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzQwNzIsIm5iZiI6MTczNTUzMzc3MiwicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTU4MzEtMTgwODg4M2MtMmMzZC00M2NmLWI3MTUtMmY2NTlkYmFhYmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODE1MDg0ZjM1M2RiOTdmNTIxNDgyOTIxNTRmOThhOGQwOTBkNWY0NzEyYzgxMGYyZTI3MTQ0OTJkMzIyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0_WR7btJk6GXonGFCTDoYz_qDtUBkjyBRinFIwRJcq4)

```js
const pages = {
    index: {
        entry: 'src/main.ts',
        template: 'index.html',
        filename: 'index.html',
        inject: {
            data: {
                title: 'mpa index'
            }
        }
    },
    apple: {
        entry: 'src/pages/apple/index.js',
        template: 'src/pages/apple/index.html',
        filename: '/pages/apple.html',
        inject: {
            data: {
                title: 'mpa apple'
            }
        }
    },
}
```

改成这样再试试，template好像不能以/开始

**Comment by lovelyJason** [comment]
> > 报错哈、
> > > error during build:
> > > Could not resolve entry module "../../../../index.html".
> > > at getRollupError (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
> > > at error (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
> > > at ModuleLoader.loadEntryModule (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
> > > at async Promise.all (index 2)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/50656459/399215831-1808883c-2c3d-43cf-b715-2f659dbaabde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzQwNzIsIm5iZiI6MTczNTUzMzc3MiwicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTU4MzEtMTgwODg4M2MtMmMzZC00M2NmLWI3MTUtMmY2NTlkYmFhYmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODE1MDg0ZjM1M2RiOTdmNTIxNDgyOTIxNTRmOThhOGQwOTBkNWY0NzEyYzgxMGYyZTI3MTQ0OTJkMzIyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0_WR7btJk6GXonGFCTDoYz_qDtUBkjyBRinFIwRJcq4)
> 
> ```js
> const pages = {
>     index: {
>         entry: 'src/main.ts',
>         template: 'index.html',
>         filename: 'index.html',
>         inject: {
>             data: {
>                 title: 'mpa index'
>             }
>         }
>     },
>     apple: {
>         entry: 'src/pages/apple/index.js',
>         template: 'src/pages/apple/index.html',
>         filename: '/pages/apple.html',
>         inject: {
>             data: {
>                 title: 'mpa apple'
>             }
>         }
>     },
> }
> ```
> 
> 改成这样再试试，template好像不能以/开始

成功了，作者大人，这个插件是不能和vite.build一起吗，是会冲突是不

**Comment by lovelyJason** [comment]
经我测试，我使用的vben5的项目， 里面配置初始化的时候会调用一个插件叫做
```ts
import { createHtmlPlugin as viteHtmlPlugin } from 'vite-plugin-html';

...
viteHtmlPlugin({ minify: true })
```

此插件会和
```ts
  mpaPlugin({
          pages,
          historyApiFallback: {
            rewrites
          }
        })， mpa调用在viteHtmlPlugin({ minify: true })后面就会出现问题
```
相互冲突，导致配置的rewrites失效从而显示主应用的vue router的404页面，在此开贴提醒大家

**Comment by yzydeveloper** [comment]
> > > 报错哈、
> > > > error during build:
> > > > Could not resolve entry module "../../../../index.html".
> > > > at getRollupError (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
> > > > at error (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
> > > > at ModuleLoader.loadEntryModule (file:///D:/projects/gamebff-frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
> > > > at async Promise.all (index 2)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/50656459/399215831-1808883c-2c3d-43cf-b715-2f659dbaabde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzQwNzIsIm5iZiI6MTczNTUzMzc3MiwicGF0aCI6Ii81MDY1NjQ1OS8zOTkyMTU4MzEtMTgwODg4M2MtMmMzZC00M2NmLWI3MTUtMmY2NTlkYmFhYmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA0NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODE1MDg0ZjM1M2RiOTdmNTIxNDgyOTIxNTRmOThhOGQwOTBkNWY0NzEyYzgxMGYyZTI3MTQ0OTJkMzIyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0_WR7btJk6GXonGFCTDoYz_qDtUBkjyBRinFIwRJcq4)
> > 
> > 
> > ```js
> > const pages = {
> >     index: {
> >         entry: 'src/main.ts',
> >         template: 'index.html',
> >         filename: 'index.html',
> >         inject: {
> >             data: {
> >                 title: 'mpa index'
> >             }
> >         }
> >     },
> >     apple: {
> >         entry: 'src/pages/apple/index.js',
> >         template: 'src/pages/apple/index.html',
> >         filename: '/pages/apple.html',
> >         inject: {
> >             data: {
> >                 title: 'mpa apple'
> >             }
> >         }
> >     },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成这样再试试，template好像不能以/开始
> 
> 成功了，作者大人，这个插件是不能和vite.build一起吗，是会冲突是不

会和你截图中的`vite.build`的配置冲突
